// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview AI-powered movie recommendations based on user input.
 *
 * - generateMovieRecommendations - A function that generates movie recommendations.
 * - GenerateMovieRecommendationsInput - The input type for the generateMovieRecommendations function.
 * - GenerateMovieRecommendationsOutput - The return type for the generateMovieRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMovieRecommendationsInputSchema = z.object({
  userInput: z
    .string()
    .describe('The user input describing the type of movie they want to watch.'),
});
export type GenerateMovieRecommendationsInput = z.infer<
  typeof GenerateMovieRecommendationsInputSchema
>;

const GenerateMovieRecommendationsOutputSchema = z.object({
  movieRecommendations: z
    .array(z.string())
    .describe('A list of movie recommendations based on the user input.'),
});
export type GenerateMovieRecommendationsOutput = z.infer<
  typeof GenerateMovieRecommendationsOutputSchema
>;

export async function generateMovieRecommendations(
  input: GenerateMovieRecommendationsInput
): Promise<GenerateMovieRecommendationsOutput> {
  return generateMovieRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMovieRecommendationsPrompt',
  input: {schema: GenerateMovieRecommendationsInputSchema},
  output: {schema: GenerateMovieRecommendationsOutputSchema},
  prompt: `You are a movie expert. Based on the user input, recommend at least 10 movies.

User Input: {{{userInput}}}

Ensure that your response is a JSON array of strings, where each string is a movie title.`,
});

const generateMovieRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateMovieRecommendationsFlow',
    inputSchema: GenerateMovieRecommendationsInputSchema,
    outputSchema: GenerateMovieRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
